myapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ajaxdepartments/$', views.subsidies_for_ajax_loop, name='ajax_loop_departments'),
    url(r'^ajaxrelation/$', views.ajax_se_relaciona_con, name='ajax_se_relaciona_con'),
    url(r'^ajaxusers/$', views.ajax_users, name='ajax_get_users'),
    url(r'^like/$', views.subsidie_like, name='like'),
    url(r'^favourites/$', views.favourites, name='favourites'),
    url(r'^new/$', views.SubvencionCreateView.as_view(), name='new_subvencion'),
    url(r'^new/responsable/$', views.ResponsableCreateView.as_view(), name='new_responsable'),
    url(r'^new/diputacion/$', views.DiputacionCreateView.as_view(), name='new_diputacion'),
    url(r'^new/generalitat/$', views.GeneralitatCreateView.as_view(), name='new_generalitat'),
    url(r'^new/estado/$', views.EstadoCreateView.as_view(), name='new_estado'),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.SubvencionUpdateView.as_view(), name='edit_subvencion'),
    url(r'^delete/(?P<slug>[\w-]+)/$', views.SubvencionDeleteView.as_view(), name='delete_subvencion'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<estado_slug>[-\w ]+)/$', views.index, name='subvencion_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.subvencion_detail, name='subvencion_detail'),
]

subvenciones/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout_then_login

from . import views

urlpatterns = [
    url(r'^logout/', logout_then_login, name='logout'),
    #url(r'^register/$', views.RegisterView.as_view(), name="register"),
    url(r'^panel/', admin.site.urls),
    url(r'^', include('myapp.urls', namespace='myapp')),
    url(r'^accounts/login/', views.custom_login, {'template_name': 'login.html'}, name='login'),
    url(r'^notifications/', include('notify.urls', namespace='notifications')),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django.db.models import Q

from .models import Subvencion, Responsable, Diputacion, Generalitat, Estado, ColorField, Gobierno
from .sites import my_admin_site

class DiputacionForm(forms.ModelForm):
    class Meta:
        model = Diputacion
        fields = ["nombre", "font_color"]

class GeneralitatForm(forms.ModelForm):
    class Meta:
        model = Generalitat
        fields = ["nombre", "font_color"]

class GobiernoForm(forms.ModelForm):
    class Meta:
        model = Gobierno
        fields = ["nombre", "font_color"]

class EstadoForm(forms.ModelForm):
    class Meta:
        model = Estado
        fields = ["etapa", "font_color"]

class ResponsableForm(forms.ModelForm):
    class Meta:
        model = Responsable
        fields = ['responsable']

#class DateInput(forms.DateInput):
 #   input_type = 'date'
  #  format = ['%Y-%m-%d']

class SubvencionForm(forms.ModelForm):
    class Meta:
        model = Subvencion
        fields = '__all__'
        widgets = {
            'inicio': forms.DateInput(format='%Y-%m-%d', attrs={'type':'date'}),
            'fin': forms.DateInput(format='%Y-%m-%d', attrs={'type':'date'}),
            'diputacion': RelatedFieldWidgetWrapper(
                Subvencion._meta.get_field('diputacion').formfield().widget,
                Subvencion._meta.get_field('diputacion').rel,
                my_admin_site,
                can_add_related=True
            ),
            'generalitat': RelatedFieldWidgetWrapper(
                Subvencion._meta.get_field('generalitat').formfield().widget,
                Subvencion._meta.get_field('generalitat').rel,
                my_admin_site,
                can_add_related=True
            ),
            'gobierno': RelatedFieldWidgetWrapper(
                Subvencion._meta.get_field('gobierno').formfield().widget,
                Subvencion._meta.get_field('gobierno').rel,
                my_admin_site,
                can_add_related=True
            ),
            'estado': RelatedFieldWidgetWrapper(
                Subvencion._meta.get_field('estado').formfield().widget,
                Subvencion._meta.get_field('estado').rel,
                my_admin_site,
                can_add_related=True
            ),
            'responsable': RelatedFieldWidgetWrapper(
                Subvencion._meta.get_field('responsable').formfield().widget,
                Subvencion._meta.get_field('responsable').rel,
                my_admin_site,
                can_add_related=True
            ),
            'se_relaciona_con': forms.CheckboxSelectMultiple(),
            'responsable': forms.CheckboxSelectMultiple(),
            'colectivo': forms.CheckboxSelectMultiple(),
        }
        exclude = ('slug', 'users_like', 'user')

    # def __init__(self, *args, **kwargs):
    #     super(SubvencionForm, self).__init__(*args, **kwargs)
    #     # access object through self.instance...
    #     self.fields['se_relaciona_con'].queryset = Subvencion.objects.filter(Q(diputacion=self.instance.diputacion) |
    #                                                                          Q(generalitat=self.instance.generalitat))

myapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core import serializers
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Count, Q
from django.db.models import DateField, Expression, F
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.decorators.http import require_POST
from django.template import loader

from notify.signals import notify
from .models import Subvencion, Estado, Diputacion, Generalitat, Responsable, Gobierno, Colectivo
from .forms import SubvencionForm, ResponsableForm, DiputacionForm, GeneralitatForm, EstadoForm

# Create your views here.
@login_required
@require_POST
def subsidie_like(request):
    subsidie_id = request.POST.get('id')
    action = request.POST.get('action')

    if subsidie_id and action:
        try:
            subsidie = Subvencion.objects.get(id=subsidie_id)
            if action == 'like':
                subsidie.users_like.add(request.user)
            else:
                subsidie.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
        return JsonResponse({'status':'ko'})

####### AJAX USERS MENTIONS IN TINYMCE ######
def ajax_users(request):
    users = User.objects.all()

    return render(request,
                  '',
                  {'users': users})

####### AJAX REQUEST SE RELACIONA CON ######
def ajax_se_relaciona_con(request):
    diputacion = request.GET.getlist('diputacion_ajax[]', '99999')
    generalitat = request.GET.getlist('generalitat_ajax[]', '99999')
    gobierno = request.GET.getlist('gobierno_ajax[]', '99999')

    query = Subvencion.objects.all().filter(Q(diputacion__pk__in=diputacion) |
                                      Q(generalitat__pk__in=generalitat) |
                                      Q(gobierno__pk__in=gobierno))
    data = serializers.serialize('json', query)
    return HttpResponse(data, content_type="application/json")

def subsidies_for_ajax_loop(request):
    subvenciones = Subvencion.objects.all()
    diputacion = Diputacion.objects.all()
    generalitat = Generalitat.objects.all()
    gobierno = Gobierno.objects.all()

    return render(request,
                  'myapp/ajax_se_relaciona_con_modal.html',
                  {'subvenciones':subvenciones,
                   'diputacion':diputacion,
                   'generalitat':generalitat,
                   'gobierno':gobierno})

class CastToDate(Expression):
    template = 'CAST( %(expressions)s AS DATE )'

    def __init__(self, expressions, output_field=None, **extra):
        output_field = output_field or DateField()
        super(CastToDate, self).__init__(expressions, **extra)
        if len(expressions) != 1:
            raise ValueError('expressions must have exactly 1 element')

@login_required()
def index(request, estado_slug=None):
    estado = None
    diputacion = None
    generalitat = None
    gobierno = None
    user = None
    estados = Estado.objects.all().annotate(number_stats=Count('subvencion'))

    # If is superuser: list all subsidies, if not, only the related to the respective user
    if request.user.is_superuser:
        subvenciones = Subvencion.objects.extra(select={"day_mod": "date(fin)"}).order_by('day_mod')
    else:
        subvenciones = Subvencion.objects.all().filter(responsable__user=request.user)

    userlikes = Subvencion.objects.filter(users_like__in=[request.user])
    total_subvenciones = Subvencion.objects.count()
    colectivos = Colectivo.objects.all()

    if estado_slug:
        if Diputacion.objects.filter(slug=estado_slug).exists():
            diputacion = get_object_or_404(Diputacion, slug=estado_slug)
            subvenciones = subvenciones.filter(diputacion=diputacion)
        elif Estado.objects.filter(slug=estado_slug).exists():
            estado = get_object_or_404(Estado, slug=estado_slug)
            subvenciones = subvenciones.filter(estado=estado)
        elif Generalitat.objects.filter(slug=estado_slug).exists():
            generalitat = get_object_or_404(Generalitat, slug=estado_slug)
            subvenciones = subvenciones.filter(generalitat=generalitat)
        elif Gobierno.objects.filter(slug=estado_slug).exists():
            gobierno = get_object_or_404(Gobierno, slug=estado_slug)
            subvenciones = subvenciones.filter(gobierno=gobierno)
        # To make it work for spaces in string(estado_slug=Juan Carlos) i modified url => r'^(?P<estado_slug>[-\w ]+)/$' => space in -\w
        elif Responsable.objects.filter(responsable=estado_slug).exists():
            user = get_object_or_404(Responsable, responsable=estado_slug)
            subvenciones = subvenciones.filter(responsable__responsable=user)
        else:
            subvenciones = Subvencion.objects.all()

    notification_list = request.user.notifications.active().prefetch()
    days_until_estado = ['7d', '6d', '5d', '4d', '3d', '2d', '1d', 'expires today', 'expired']

    return render(request,
                  'myapp/index.html',
                  {'estado': estado,
                   'diputacion': diputacion,
                   'generalitat': generalitat,
                   'gobierno': gobierno,
                   'user': user,
                   'estados': estados,
                   'subvenciones': subvenciones,
                   'days_until_estado': days_until_estado,
                   'notifications': notification_list,
                   'total_subvenciones': total_subvenciones,
                   'colectivos': colectivos,
                   'userlikes': userlikes})

# Favourites subsidies on each user
@login_required()
def favourites(request, estado_slug=None):
    estado = None
    diputacion = None
    generalitat = None
    gobierno = None
    user = None
    estados = Estado.objects.all().annotate(number_stats=Count('subvencion'))

    total_subvenciones = Subvencion.objects.count()
    colectivos = Colectivo.objects.all()

    subvenciones = Subvencion.objects.filter(users_like__in=[request.user])
    userlikes = Subvencion.objects.filter(users_like__in=[request.user])

    if estado_slug:
        if Diputacion.objects.filter(slug=estado_slug).exists():
            diputacion = get_object_or_404(Diputacion, slug=estado_slug)
            subvenciones = subvenciones.filter(diputacion=diputacion)
        elif Estado.objects.filter(slug=estado_slug).exists():
            estado = get_object_or_404(Estado, slug=estado_slug)
            subvenciones = subvenciones.filter(estado=estado)
        elif Generalitat.objects.filter(slug=estado_slug).exists():
            generalitat = get_object_or_404(Generalitat, slug=estado_slug)
            subvenciones = subvenciones.filter(generalitat=generalitat)
        elif Gobierno.objects.filter(slug=estado_slug).exists():
            gobierno = get_object_or_404(Gobierno, slug=estado_slug)
            subvenciones = subvenciones.filter(gobierno=gobierno)
        # To make it work for spaces in string(estado_slug=Juan Carlos) i modified url => r'^(?P<estado_slug>[-\w ]+)/$' => space in -\w
        elif Responsable.objects.filter(responsable=estado_slug).exists():
            user = get_object_or_404(Responsable, responsable=estado_slug)
            subvenciones = subvenciones.filter(responsable__responsable=user)
        else:
            subvenciones = Subvencion.objects.all()

    notification_list = request.user.notifications.active().prefetch()
    days_until_estado = ['7d', '6d', '5d', '4d', '3d', '2d', '1d', 'expires today', 'expired']

    return render(request,
                  'myapp/index.html',
                  {'estado': estado,
                   'diputacion': diputacion,
                   'generalitat': generalitat,
                   'gobierno': gobierno,
                   'user': user,
                   'estados': estados,
                   'days_until_estado': days_until_estado,
                   'notifications': notification_list,
                   'total_subvenciones': total_subvenciones,
                   'colectivos': colectivos,
                   'subvenciones': subvenciones,
                   'userlikes': userlikes})

@login_required()
def subvencion_by_user(request, name_slug):
    #Subvencion.objects.filter(responsable__responsable='Juan Carlos')
    subsidiers = None
    estados = Estado.objects.all().annotate(number_stats=Count('subvencion'))
    subvenciones = Subvencion.objects.all()

    if name_slug:
        subsidiers = get_object_or_404(Responsable, responsable=name_slug)
        subvenciones = subvenciones.filter(responsable__responsable=subsidiers)

    notification_list = request.user.notifications.active().prefetch()
    days_until_estado = ['7d', '6d', '5d', '4d', '3d', '2d', '1d', 'expires today', 'expired']

    return render(request,
                  'myapp/index.html',
                  {'subsidiers': subsidiers,
                   'estados': estados,
                   'subvenciones': subvenciones,
                   'days_until_estado': days_until_estado,
                   'notifications': notification_list})

@login_required()
def subvencion_detail(request, id, slug):
    userlikes = Subvencion.objects.filter(users_like__in=[request.user])
    subvencion = get_object_or_404(Subvencion,
                                   id=id,
                                   slug=slug)


myapp/templates/myapp/ajax_se_relaciona_con_modal.html
<div class="row">
    {% if diputacion %}
        <div class="col-4-md" style="margin-left:10px;margin-right:10px;">
            <!-- Filter Diputacion de Alicante -->
            <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                <label>Diputación de Alicante:</label>
                <ul class="form-control modal-ajax-entes" style="list-style-type: none">
                    {% for dip in diputacion %}
                        <li>
                            <label for="{{ dip.nombre }}_{{ dip.pk }}">
                                <input name="diputacion_ajax" id="{{ dip.nombre }}_{{ dip.pk }}" type="checkbox" value="{{ dip.pk }}">{{ dip.nombre }}
                            </label>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    {% if generalitat %}
        <div class="col-4-md" style="margin-left:10px;margin-right:10px;">
            <!-- Filter Generalitat -->
            <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                <label>Generalitat Valenciana:</label>
                <ul class="form-control modal-ajax-entes" style="list-style-type: none">
                    {% for gene in generalitat %}
                        <li>
                            <label for="{{ gene.nombre }}_{{ gene.pk }}">
                                <input name="generalitat_ajax" id="{{ gene.nombre }}_{{ gene.pk }}" type="checkbox" value="{{ gene.pk }}">{{ gene.nombre }}
                            </label>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    {% if gobierno %}
        <div class="col-4-md" style="margin-left:10px;margin-right:10px;">
            <!-- Filter Gobierno -->
            <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                <label>Gobierno de España:</label>
                <ul class="form-control modal-ajax-entes" style="list-style-type: none">
                    {% for gob in gobierno %}
                        <li>
                            <label for="{{ gob.nombre }}_{{ gob.pk }}">
                                <input name="gobierno_ajax" id="{{ gob.nombre }}_{{ gob.pk }}" type="checkbox" value="{{ gob.pk }}">{{ gob.nombre }}
                            </label>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
</div>

<div class="row">
    <div class="col-12-md content-ajax-body form-group">
        <ul id="content_ajax_list"></ul>
    </div>
</div>

myapp/templates/myapp/diputacion_create.html
{% extends "myapp/base.html" %}
{% block content %}

    {% load staticfiles %}
    {% load tags %}
    <div class="row">
        <div class="col">
        </div>
        <div class="ag_create_post_wrapper col">
            <h1>Añadir Departamento (Diputación)</h1>

            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="">{% csrf_token %}

                {% if form.errors %}
                    <div class="ag_form_login_message_error">
                        {% for field,error in form.errors.items %}
                            {{ field|capfirst }} - {{ error|striptags }}
                        {% endfor %}
                    </div>
                {% endif %}

                <!-- Diputacion -->
                <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                    {{ form.nombre.label_tag }}
                    {{ form.nombre|htmlattributes:"class:form-control" }}
                </div>

                <!-- Font color -->
                <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                    {{ form.font_color.label_tag }}
                    {{ form.font_color|htmlattributes:"class:form-control" }}
                </div>

                <input onclick="this.disabled=true,this.form.submit();" class="button_submit_create_form" type="submit" value="Crear Departamento" />
                <a href="{% url 'myapp:new_subvencion' %}"><button type="button" class="btn btn-info">Volver</button></a>
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
                {% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
            </form>
        </div>
        <div class="col"></div>

    </div>
{% endblock %}

myapp/templates/myapp/estado_create.html
{% extends "myapp/base.html" %}
{% block content %}

    {% load staticfiles %}
    {% load tags %}
    <div class="row">
        <div class="col">
        </div>
        <div class="ag_create_post_wrapper col">
            <h1>Añadir Estado</h1>

            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="">{% csrf_token %}

                {% if form.errors %}
                    <div class="ag_form_login_message_error">
                        {% for field,error in form.errors.items %}
                            {{ field|capfirst }} - {{ error|striptags }}
                        {% endfor %}
                    </div>
                {% endif %}

                <!-- Estado -->
                <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                    {{ form.etapa.label_tag }}
                    {{ form.etapa|htmlattributes:"class:form-control" }}
                </div>

                <!-- Font color -->
                <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                    {{ form.font_color.label_tag }}
                    {{ form.font_color|htmlattributes:"class:form-control" }}
                </div>

                <input onclick="this.disabled=true,this.form.submit();" class="button_submit_create_form" type="submit" value="Crear Estado" />
                <a href="{% url 'myapp:new_subvencion' %}"><button type="button" class="btn btn-info">Volver</button></a>
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
                {% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
            </form>
        </div>
        <div class="col"></div>

    </div>
{% endblock %}

myapp/templates/myapp/generalitat_create.html
{% extends "myapp/base.html" %}
{% block content %}

    {% load staticfiles %}
    {% load tags %}
    <div class="row">
        <div class="col">
        </div>
        <div class="ag_create_post_wrapper col">
            <h1>Añadir Departamento (Generalitat)</h1>

            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="">{% csrf_token %}

                {% if form.errors %}
                    <div class="ag_form_login_message_error">
                        {% for field,error in form.errors.items %}
                            {{ field|capfirst }} - {{ error|striptags }}
                        {% endfor %}
                    </div>
                {% endif %}

                <!-- Generalitat -->
                <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                    {{ form.nombre.label_tag }}
                    {{ form.nombre|htmlattributes:"class:form-control" }}
                </div>

                <!-- Font color -->
                <div class="form-group title-create_post" style="text-align:justify;font-weight:bold;">
                    {{ form.font_color.label_tag }}
                    {{ form.font_color|htmlattributes:"class:form-control" }}
                </div>

                <input onclick="this.disabled=true,this.form.submit();" class="button_submit_create_form" type="submit" value="Crear Departamento" />
                <a href="{% url 'myapp:new_subvencion' %}"><button type="button" class="btn btn-info">Volver</button></a>
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
                {% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
            </form>
        </div>
        <div class="col"></div>

    </div>
{% endblock %}

myapp/templates/myapp/navbar.html
<nav class="navbar navbar-expand-sm navbar-custom fixed-top">
    <div class="row">
        <div class="col brand-styled-nav">
            <a data-toggle="collapse" href="#dep-notif-collapse" class="navbar-brand">Gestión de Subvenciones</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom">
                <i class="fa fa-bars fa-lg py-1 text-white"></i>
            </button>
        </div>
    </div>

    <div class="navbar-collapse collapse" id="navbarCustom">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myapp:index' %}"> <i class="fas fa-home"></i> Inicio</a>
            </li>
            <li class="nav-item {% if request.path == '/new/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'myapp:new_subvencion' %}"> <i class="far fa-file"></i> Crear subvención</a>
            </li>
            <li class="nav-item">
                <!-- Index, Cuando creas y cuando pinchas en favoritos aparecerá el contador de cuántas favortias tengo -->
                <!-- También Diputación, Estado, Gobierno, Generalitat, Responsable -->
                {% url 'myapp:subvencion_by_category' estado.slug as estado %}
                {% url 'myapp:subvencion_by_category' diputacion.slug as diputacion %}
                {% url 'myapp:subvencion_by_category' generalitat.slug as generalitat %}
                {% url 'myapp:subvencion_by_category' gobierno.slug as gobierno %}
                {% url 'myapp:subvencion_by_category' responsable__responsable.responsable as responsable %}

                {% url 'myapp:subvencion_detail' subvencion.id subvencion.slug as detail %}
                {% url 'myapp:edit_subvencion' subvencion.slug as editsubv %}
                {% url 'myapp:delete_subvencion' subvencion.slug as delsubv %}
                {% if request.path == '/' or request.path == '/new/' or request.path == '/favourites/' or request.path == estado or request.path == diputacion or request.path == generalitat or request.path == gobierno or request.get_full_path == responsable %}
                    <a id="indexFavouritesButton" class="nav-link" href="{% url 'myapp:favourites' %}">
                        <span id="badge-count-likes" class="badge">{{ userlikes.count }}</span>
                        <i class="far fa-bookmark"></i> Ver favoritos
                    </a>
                <!-- En detalles, al editar, borrar la subvención aparecerá como favorita o no -->
                {% elif request.path == detail or request.path == editsubv or request.path == delsubv %}
                    {% with total_likes=subvencion.users_like.count users_like=subvencion.users_like.all %}
                        <a class="nav-link like-button-details" href="#" data-id="{{ subvencion.id }}" data-action="{% if request.user in users_like %}un{% endif %}like">
                            <i class="likes_heart {% if request.user in users_like %}fas{% else %}far{% endif %} fa-bookmark"></i> Ver favoritos
                        </a>
                    {% endwith %}
                {% else %}
                    <a id="indexFavouritesButton" class="nav-link" href="{% url 'myapp:favourites' %}">
                        <span id="badge-count-likes" class="badge">{{ userlikes.count }}</span>
                        <i class="far fa-bookmark"></i> Ver favoritos
                    </a>
                {% endif %}
            </li>
            <!--<li class="nav-item">
                <a href="#" id="news" class="nav-link">
                    <i class="fa fa-bell"></i>
                    <span class="button__badge">1</span>
                </a>

                <div style="display:none" class="alert_list">
                    <ul class="unstyled">
                        <li class="alert_li">
                            Notificaciones
                        </li>
                    </ul>
                </div>
            </li>-->
        </ul>

        <ul class="navbar-nav" style="margin-right:30px;">
            {% if request.user.is_authenticated %}
                <li class="nav-item" style="margin-right:20px;margin-top: 8px;">
                    <span id="button-actual-subsidie-navigation"><i class="fas fa-exchange-alt"></i></span>
                </li>
                <li class="nav-item" style="margin-right:20px;">
                    <input type="text" id="search-on-navigation">
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"> <i class="far fa-user"></i> {{ request.user.username|title }}</a>
                </li>
            {% else %}
                <li class="nav-link" class="nav-item">Bienvenido nuevo usuario. Por favor inicie sesión</li>
            {% endif %}

            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}"> <i class="fas fa-sign-out-alt"></i> Salir</a></li>
        </ul>
    </div>
</nav>

myapp/templates/myapp/responsable_create.html
{% extends "myapp/base.html" %}
{% block content %}

    {% load staticfiles %}
    {% load tags %}
    <div class="row">
        <div class="col">
        </div>
        <div class="ag_create_post_wrapper col">
            <h1>Añadir Responsable</h1>

            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="">{% csrf_token %}

                {% if form.errors %}
                    <div class="ag_form_login_message_error">
                        {% for field,error in form.errors.items %}
                            {{ field|capfirst }} - {{ error|striptags }}
                        {% endfor %}
                    </div>
                {% endif %}

                <!-- Responsable -->
                <div class="input-group title-create_post">
                    {{ form.responsable|htmlattributes:"class:form-control" }}
                </div>

                <input onclick="this.disabled=true,this.form.submit();" class="button_submit_create_form" type="submit" value="Crear Responsable" />
                <a href="{% url 'myapp:new_subvencion' %}"><button type="button" class="btn btn-info">Volver</button></a>
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            </form>
        </div>
        <div class="col"></div>

    </div>
{% endblock %}

myapp/templates/myapp/subv_email_create.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2>Gestión de subvenciones</h2>
        {% if created == True %}
            <i><b>{{ name_actor }}</b></i> ha creado una nueva subvención: <a href="subvenciones.amosdev.eu/{{ object.id }}/{{ object.slug }}/">{{ name_subv }}</a>
        {% else %}
            <i><b>{{ name_actor }}</b></i> ha modificado una subvención: <a href="subvenciones.amosdev.eu/{{ object.id }}/{{ object.slug }}/">{{ name_subv }}</a>
        {% endif %}
    </body>
</html>